# Generated by Django 3.1.7 on 2021-03-02 14:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('sbs', '0002_auto_20210228_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='VideoFiles',
        ),
    ]
