# Generated by Django 3.1.7 on 2021-03-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0003_auto_20210302_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.CharField(default='no description', max_length=500),
        ),
        migrations.AlterField(
            model_name='channel',
            name='links',
            field=models.CharField(default='kg.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='vdetails',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnail/'),
        ),
    ]
