# Generated by Django 3.1.7 on 2021-03-03 06:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sbs', '0004_auto_20210302_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=50)),
                ('Quantity', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('status', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vdetails',
            name='vfile',
        ),
        migrations.RemoveField(
            model_name='videofiles',
            name='channel',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='vdetails',
        ),
        migrations.DeleteModel(
            name='VideoFiles',
        ),
    ]
